### ISSUE TITLE
orbclient is blocking until a new event receives

### ISSUE THREAD

**Issue by FloVanGH** [redox-os/orbclient#41]
Could it be that the orbclient window is blocking (waiting) until it receives a new event (https://github.com/redox-os/orbclient/blob/master/src/sys/sdl2.rs#L361). This should be critical if we want to integrate animations in orbtk or to handle NPCs in orbgame. I can reproduce his behavior in orbgame. The game stops until a new event received.

**Comment by robbycerantola** [comment]
@FloVanGH  Not really and issue of orbclient. If you create the window with the Async WindowFlag, then the window is non blocking. See my PR for orbgame. I hope you like it .
